### ISSUE TITLE
Easy way to change the main color?

### ISSUE THREAD

**Issue by r-richmond** [textbook/bulrush#12]
I was poking around the theme trying to find an easy way to change main color and came across https://github.com/textbook/bulrush/blob/master/static/css/main.less#L4

However [changing](https://github.com/r-richmond/r-richmond.github.io/blob/master/theme/css/main.less#L4) that value didn't seem to [do anything](http://justnumbersandthings.com/2017-03-03-Pelican-Intro.html).. What am I missing?

**Comment by mohammad-rahchamani** [comment]
the main color comes from https://cdnjs.cloudflare.com/ajax/libs/bulma/0.3.1/css/bulma.min.css so changing the value does nothing.
you should add a css file to your site and override color.

**Comment by textbook** [comment]
That's just a *copy* of the primary colour from Bulma, to make it more obvious what is also being set to that colour. If you want to override it it's used in relatively few places in the theme, see e.g. https://github.com/textbook/textbook.github.io-source/blob/d772c430ff676e471cfac69a06549a4bfe424f2c/content/extra/custom.css, where #4abdac is the new primary colour. The only way to override it globally would be to `@import` the Bulma styles in `main.less` rather than include them from the CDN in `base.html`.
