### ISSUE TITLE
document way to change colors

### ISSUE THREAD

**Issue by deutrino** [textbook/bulrush#18]
As a user who hasn't touched front end development for a couple years and picked this theme off the shelf because I liked its looks, I would like to be able to quickly and easily change the colors, starting with the most obvious ('primary') color. It would be *really* great if the words 'npm install' were not within a light year of a viable solution to this.

I saw issue #12 but don't really understand it as I am not familiar with the (evidently teeming) ecosystem of programs involved in generating CSS these days - I just want to change the default color on my blog.

(Overriding with the example of `content/extra/custom.css` I do understand, but either I'm looking in the wrong places, or the Bulma docs are lacking on which classes would be best overridden.)

**Comment by textbook** [comment]
The Bulma colour scheme is designed to be overridden from the Sass side, see e.g. [the customisation docs](https://bulma.io/documentation/overview/customize/), which isn't easy do hook into in a static site generator. As a rule of thumb, you can tell which Bulma classes are associated with colours because they have examples of changing the colour with e.g. `is-info` (like the [button](https://bulma.io/documentation/elements/button/#colors)). You can also just inspect the site in your browser to see what's going on. 

That said I've already done that, so the stylesheet in my personal blog linked from #12 is a more-or-less complete list of the classes you need to override; it covers everything that uses the primary colour, for example. I'd recommend you copy that into your own site verbatim, then you can just change the colours in that file. 

Thanks for the suggestion, I'll have a think about how I can make it clearer in the appropriate section of the README.

**Comment by deutrino** [comment]
Yeah, I put another 90 min in on learning just enough to determine that it's too much work / too many moving parts for me. I could change '@primary' in main.less to a color of my choosing, but the output only overrode a few classes with it, and the color of the banner, the headings, etc., didn't change. The lowest-effort thing to do for now might be to warn users in the docs that if they want to change the default colors, they will need to know what they're doing.

**Comment by textbook** [comment]
Note that that's *exactly what I'm saying in the other issue*, the `@primary` colour in `main.less` **does not override Bulma**. It's a *copy* of Bulma's existing primary colour, so you can see what things *not set by Bulma* I'm making that colour.

However, the overall point is that you shouldn't need to edit the theme's files at all, unless you really want to and know what you're doing. That's why I added the provision for [custom styling](https://github.com/textbook/bulrush#custom-styling), which *is* documented, so you can add your own file that overrides whatever you want *without* having to delve into the theme code. And, again, the resulting overrides for my own blog (https://blog.jonrshar.pe) are [relatively short](https://github.com/textbook/textbook.github.io-source/blob/5f0a6c1f7ef061b2f7d1f53178221ae10cab23d2/content/extra/custom.css); there aren't that many places that need overriding.

So I'd suggest you literally just copy that file into your own project, [reference it in the config](https://github.com/textbook/textbook.github.io-source/blob/5f0a6c1f7ef061b2f7d1f53178221ae10cab23d2/pelicanconf.py#L66), and start making changes from there. You shouldn't need to touch Bulrush's files at all.
