### ISSUE TITLE
Layout and text of right-menu bar

### ISSUE THREAD

**Issue by philshem** [textbook/bulrush#23]
Showing "Other Pages" above "Links" and "Social" seems to be out of order, especially since most people won't use Atom/RSS.

<img width="224" alt="image" src="https://user-images.githubusercontent.com/4997607/59030237-b23b9d00-8860-11e9-9386-6453e79603c5.png">

I'd propose a setting in `pelicanconf.py` that allows the user to rename these titles (aka "Other Pages" becomes "Feeds") and also change the order of items on the right-menu bar.

**Comment by textbook** [comment]
Looking at the current docs, there could be an `OTHER_PAGES_WIDGET_NAME` to go with e.g. [`LINKS_WIDGET_NAME`][1]. Alternatively, the name could change automatically to Feeds if there are no Other Pages.

The default theme actually groups the feeds into Social, not Other Pages: [`base.html`][2]. That would also push it below Links and the rest of Social in Bulrush.

I don't really want to get into dynamic re-ordering because I think that could quickly get pretty complex.

  [1]: https://docs.getpelican.com/en/stable/settings.html?highlight=links#LINKS_WIDGET_NAME
  [2]: https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/base.html#L49-L65
